build.sh
以下の処理が足りていなかったので追加。
・他環境でリポジトリをclone した時にcomposer依存パッケージのインストールをする処理
・Laravel プロジェクトディレクトリの権限を再設定する処理
・APP_KEY を再作成する処理を追加
APP_KEY 作成については以下サイトを参考。
https://stackoverflow.com/questions/33370134/when-to-generate-a-new-application-key-in-laravel
=> build 時に500 エラーが返ってくる障害を修正(#15 の改修)

a6s-cloud/app/Article.php, a6s-cloud/app/Http/Controllers/ArticleController.php, a6s-cloud/database/migrations/2019_02_23_131522_create_articles_table.php, a6s-cloud/database/seeds/ArticlesTableSeeder.php, a6s-cloud/routes/api.php, build.sh
(#18 のプルリクエスト(#19)の派生から作成したので、そちらを先にマージしてもらえると助かります)
issue #7 のプルリクエストです。
Laravel にはREST API 用の枠組みが既に用意されているようで、勝手にJSON に書式変更してレスポンスを返してくれるようでした。
そのため、#11 も同時にクローズできそうです。
=> Create proto connects db#7

a6s-cloud/app/Http/Controllers/AnalysisResultListsController.php, a6s-cloud/routes/api.php
close #35 
とりあえず、動くようになりました。Laravelの書き方が分かっていないので、修正ありきです。。
レスポンスはpagenationの関係上、設計案から変更になっております。
`curl http://localhost/api/v1/AnalysisResultLists?serach_word=6 回目&page=1`
で動くと思います。
- 1ページあたり100件
- serach_wordとpageは省略可
=> AnalysisResultListsのプロトタイプAPI作成

build.sh
* GRANT は常にテーブル作成後に実施するように修正
* テーブルが存在しない状態でテーブル削除処理をしても戻り値0 となるように修正
=> 完全に新規な環境でbuild.sh を実行するとbuild に失敗する事象を修正 Close #43

a6s-cloud/database/migrations/2019_04_04_135123_alter_charcter_utf8mb4.php, build.sh
#38 のissue に関連。
laravel のマイグレーションで自動的にanalysis_results, tweets テーブルをutf8mb4 に変換するように修正。
=> analysis_results, tweets テーブルをutf8mb4 に変換するように修正

a6s-cloud/.env.example
#58  の対応をしました。
`.env.example`に項目が追加されていること。
close #58
=> Twitter APIキーのサンプル項目を追加

a6s-cloud/database/migrations/2019_04_10_133933_add_column_analysis_results_table.php
#41 の内容を修正しました👨‍🔧
analysis_resultsテーブルにurlとretweet_countを追加しました👨‍🔧
`./build.sh`を実行して、analysis_resultsテーブルにurlとretweet_countを追加されていることの確認をお願いします👨‍🔧
close #41
なし
なし
=> analysis_resultsテーブルにカラムを追加👨‍🔧

a6s-cloud/app/Http/Controllers/AnalysisRequestsController.php
#67 の内容を修正しました。
start_dateを1週間前以上にして（tweet件数が0件）、レスポンスがエラーにならないことを確認お願いします。
close #67
なし
とりあえず、エラーにならないようバリデーションを入れましたが、もう少し処理順を工夫したら綺麗になりそうです。。
=> 初回0件の場合のエラー対応

a6s-cloud/routes/api.php
#74 の内容を修正しました。
`curl http://localhost/api/v1/AnalysisResults/1` 等でアクセスして、レスポンスが返ってくることの確認お願いします。
close #74
なし
もう少し進めたかったけど、今日は限界でした。。
=> AnalysisResults APIのrouter作成

a6s-cloud/app/Http/Controllers/AnalysisResultsController.php
#77 の内容を対応しました。
`http://localhost/api/v1/AnalysisResults/101` (数字はanalysis_resultsのidを指定)を叩いてレスポンスにuser_rankingが入っていることを確認お願いします。
close #75
close #76 
close #77
とくになし
必要なAPIは形ができてきた予感😊
（テストしていないのですが笑）
=> 【AnalysisResults API】user_rankingを追加

a6s-cloud/app/Http/Controllers/AnalysisRequestsController.php
API で取得されたTweet 日時がUTC になっているので、JST に修正
リクエストを飛ばして、DB の結果を確認。
例) なおとさんの旅行のツイートを使わせていただきました🙇‍♂️
```
for d in 2019-04-18 2019-04-19 2019-04-20; do
echo -en "start_date=${d}&analysis_word=#なおとの気まぐれ伊豆旅行&url=https://example.com&analysis_timing=[1,3]" | curl http://localhost/api/v1/AnalysisRequests --data-binary @-
done
```
DB の内容を確認
```
mysql> SELECT id,user_account,SUBSTR(text, 1, 12),created_at,insert_date,update_date FROM tweets WHERE user_account = 'naoto_7713' ORDER BY created_at;
+------+--------------+--------------------------------------+---------------------+---------------------+---------------------+
| id   | user_account | SUBSTR(text, 1, 12)                  | created_at          | insert_date         | update_date         | …
```
=> Tweet のタイムゾーンをUTC からJST に変更

a6s-cloud/database/seeds/AnalysisResultsTableSeeder.php, a6s-cloud/database/seeds/TweetsTableSeeder.php
#101 の内容を修正しました。
analysis_resultsは1件のみに変更しました。（バックエンドでデータ作成できるため）
`./build.sh` を実行してテストデータの確認お願いします。
close #101
特になし
tweetsのデータの作成方法勉強になりました！！（analysis_result_idのところ）
僕なら何も考えず2重ループ使っちゃいそうです😇
=> seedファイル修正

a6s-cloud/composer.json, a6s-cloud/composer.lock, a6s-cloud/database/migrations/2019_04_27_041144_alter_type_of_image_field.php
#92 の内容を修正しました
build.sh を実行させた後に、analysis_results テーブルのimage フィールドがvarchar(255) になっていることを確認。
close #60
close #92
なし
migration ファイルだけ作成してmigration を実行すると以下のようなエラーが出ました。
```
RuntimeException  : Changing columns for table "analysis_results" requires Doctrine DBAL; install "doctrine/dbal".
```
なので`doctrine/dbal` 追加しておきました。
```
composer require doctrine/dbal
```
migration 後の結果は以下のようになります。
```
mysql> describe analysis_results;
+---------------------+---------------------+------+-----+-------------------+-----------------------------------------------+
| Field               | Type                | Null | Key | Default           | Extra                                         |
+---------------------+---------------------+------+-----+-------------------+------------------------------------------- …
```
=> image フィールドをvarchar(255) に変更するmigration を追加

a6s-cloud/app/Facades/AnalysisRequestService.php, a6s-cloud/app/Facades/TwitterClientService.php, a6s-cloud/app/Http/Controllers/AnalysisRequestsController.php, a6s-cloud/app/Providers/AppServiceProvider.php, a6s-cloud/app/Services/AnalysisRequestService.php, a6s-cloud/app/Services/TwitterClientService.php, a6s-cloud/config/app.php
#111 の内容を修正しました。
ペアプロしながら確認したのでサラッと確認お願いします。
close #111
特になし
つとむさん、なおとでペアプロしました。
=> AnalysisRequestsControllerのリファクタリング

a6s-cloud/app/Services/AnalysisRequestService.php
#55 の内容を修正しました。
解析依頼をして、storage/app以下にtweet fileが存在しなことの確認お願いします。
close #55
とくになし
pythonバッチを実行する関数の最後に入れてみました！
=> tweet fileの削除(平成最後のプルリクです。)

a6s-cloud/app/Services/TwitterClientService.php
#123  の内容を修正しました。
通常通り動くかの確認で大丈夫です
close #123 
text fileが存在しない場合、batch実行するとエラーになる
#124 
とくになし
https://github.com/abraham/twitteroauth/blob/master/src/TwitterOAuth.php
http://westplain.sakuraweb.com/translate/twitter/Documentation/REST-APIs/Public-API/GET-search-tweets.cgi
=> リクエスト回数のチェック

a6s-cloud/database/migrations/2019_05_06_132030_create_black_analysis_words.php
#140 の内容を修正しました。
build.sh を実行してblack_analysis_words テーブルが作成されていることを確認してください。
close #140
なし
以下のような感じでテーブルが作成されると思います。
```
mysql> describe black_analysis_words;
+-------------------+---------------------+------+-----+-------------------+-----------------------------------------------+
| Field             | Type                | Null | Key | Default           | Extra                                         |
+-------------------+---------------------+------+-----+-------------------+-----------------------------------------------+
| id                | bigint(20) unsigned | NO   | PRI | NULL              | auto_increment                                |
| analysis_ng_word  | varchar(255)        | NO   | UNI | NULL              |                                               |
| …
```
=> black_analysis_words テーブルを作成するmigration を作成

a6s-cloud/public/swagger-ui/swagger.yml
#144 の内容を修正しました。
swagger仕様書でAnalysisRequestsが追加されていることの確認をお願いします。
close #144 
とくになし
とくになし
=> 解析依頼のAPI仕様書を作成

a6s-cloud/public/swagger-ui/swagger.yml
#145 の内容を修正しました。
swaggerのAnalysisResultListsが更新されているか確認お願いします。
close #145
とくになし
laravelのpagenationで追加される項目がよく分からなかったの詳細まで書いていないです。。
=> AnalysisResultListsのswaggerを追加

docker/laravel/Dockerfile, docker/laravel/grouscope_entrypoint.sh, docker/nginx/Dockerfile, docker/nginx/default.conf
#166 の内容に対応しました
以下bash で実施してください。
```
docker network create a6s
docker run --rm --name laravel --volume ${PWD}/a6s-cloud:/var/www/html/a6s-cloud --net a6s a6scloud/grouscope-laravel:testing
```
別ターミナルで以下のコマンドを実行する
```
docker rm nginx && docker rmi a6scloud/grouscope-nginx:testing
docker run --rm --name nginx --net a6s -p 80:80 a6scloud/grouscope-nginx:testing
```
http://localhost にブラウザでアクセスしてLaravel のトップ画面が見れること。
close #166
なし
なし
=> #166 のissue に対応しました

a6s-cloud/app/Services/AnalysisRequestService.php, a6s-cloud/composer.json, a6s-cloud/requirements.txt, docker/laravel/Dockerfile, docker/laravel/grouscope_entrypoint.sh, docker/laravel/install_git_modules.sh, docker/mysql/Dockerfile, docker/mysql/docker-entrypoint-initdb.d/10_initialize_db.sql
#168 の内容を修正しました。
My SQL, Laravel コンテナはリポジトリのルートで実行してください。
My SQL コンテナを起動。
```
docker stop mysql
docker rm mysql
docker run --rm --net a6s --name mysql \
-v ${PWD}/docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d \
-e MYSQL_ROOT_PASSWORD=secret -ti mysql:8
```
Laravel コンテナを起動。
```
docker rmi a6scloud/grouscope-laravel:testing
docker run --rm --name laravel --hostname laravel --net a6s \
--volume ${PWD}/a6s-cloud:/var/www/html/a6s-cloud \
-e CONSUMER_KEY=${CONSUMER_KEY} \
-e CONSUMER_SECRET="${CONSUMER_SECRET}" \
-e ACCESS_TOKEN="${ACCESS_TOKEN}" \
-e ACCESS_TOKEN_SECRET="${ACCESS_TOKEN_SECRET}" \
-e DB_HOST=mysql \
-e DB_DATABASE=a6s_cloud \
-e DB_USERNAME=default \
-e DB_PASSWORD=secret \
-ti a6scloud/grouscope-laravel:testing
// CONSUMER_KEY, CONSUMER_SECRET, …
```
=> MySQL 環境を作成

.env, docker-compose.yml, docker/laravel/Dockerfile, docker/laravel/grouscope_entrypoint.sh, docker/laravel/wait_until_mysql_started.sh
#170 に対応しました。
.env (a6s-cloud 直下のではない)内の以下の変数を`testing` に変更してください。
```
NGINX_IMAGE_TAG=testing
LARAVEL_IMAGE_TAG=testing
```
.env (a6s-cloud 直下のではない)内の以下の変数をTwitter API の適切な値に設定してください。
```
CONSUMER_KEY=...
CONSUMER_SECRET=...
ACCESS_TOKEN=...
ACCESS_TOKEN_SECRET=...
```
以下のコマンドを実行してコンテナを起動してください。
```
docker-compose rm -f
docker-compose pull
docker-compose up
> grouscope_laravel が"NOTICE: ready to handle connections" と表示するまで待つ
```
テストコマンドを実行して画像が作成されることを確認してください(以下は例)。
```
echo -en 'start_date=2019-07-23&analysis_word=#Google&url=https://github.com/nsuzuki7713/a6s-cloud-front/&analysis_timing=[1,3]' | curl http://localhost/api/v1/AnalysisRequests --data-binary @- > ~/result.html
```
(任意)お使いのMySQL クライアント(コマンドでもOK)を使って`127.0.0.1:3389` に接続できて各テーブルが見えること。
close #170
なし …
=> 開発環境をdocker-compose 化しました

.gitmodules, a6s-cloud/.env.example, a6s-cloud/app/Services/AnalysisRequestService.php, a6s-cloud/composer.json, docker-compose.yml, docker/build.sh, docker/laravel/Dockerfile, docker/laravel/grouscope_entrypoint.sh
#174 の内容を修正しました
今までと同様に動くことを確認お願いします。
```
cd grouscope-backend
```
.env 内の以下の場所を正しいやつに修正する。
```
CONSUMER_KEY=xxxxx
CONSUMER_SECRET=xxxxx
ACCESS_TOKEN=xxxxx
ACCESS_TOKEN_SECRET=xxxxx
```
起動する。
```
docker-compose up
```
動作確認する(以下は例)。
```
echo -en 'start_date=2019-08-04&analysis_word=#Apple&url=https://github.com/nsuzuki7713/a6s-cloud-front/&analysis_timing=[1,3]' \
| curl http://localhost/api/v1/AnalysisRequests --data-binary @- > ~/result.html
```
今までどおり、画像が作成されていることを確認してください。
close #174
お時間ある時で構わないので、ご確認お願いします。
特になし
=> Git リポジトリの依存関係をgit submodule で管理するように修正
