a6s-cloud/grouscope-backend

a6s-cloud/app/Http/Kernel.php
a6s-cloud/app/Http/Middleware/Cors.php

いくつか方式はありそうでしたが、middleware
を使って解決する方法にしてみました。
Access-Control-Allow-Origin: の値を"*"
としていますが、仮の値です。今後検証環境や本番環境のFQDN
が固まってきた時に厳密に決めるべきと思います。
参考にしたサイトは以下:
https://stackoverflow.com/questions/39429462/adding-access-control-allow-origin-header-response-in-laravel-5-3-passport
https://www.youtube.com/watch?v=1U74kJKy9XU
一応、レスポンスにAccess-Control-Allow-Origin ヘッダが追加されていることは確認しましたので、お時間あるときになおとさんのお手元でご確認いただければと思います！

レスポンス時にAccess-Control-Allow-Origin ヘッダをつけるように設定

---

build.sh

現状workspace(PHP/Laravel), mysql
環境のコンテナはタイムゾーンの設定が反映されますが、laradock のdocker-compose
を見た所、nginxコンテナのタイムゾーンは設定しないようになっているみたいです(UTC のまま)。
nginxについてはタイムゾーンを設定しないようになっている理由などを時間ある時に調査してみようと思いますが、本件は我々側の問題ではないのでプルリクエストさせてもらいました。

タイムゾーンをAsia/Tokyo に設定 #26

---

.gitmodules

以下コマンドを実行してlaradock
ディレクトリ以下のファイルに変更があった時にstatus
表示されないようにしました。
git config --file .gitmodules submodule.laradock.ignore dirty
...当初.gitignore
に追加すれば良いと思っていましたが、それでは消えませんでした(想定外)。
https://rcmdnk.com/blog/2013/10/18/computer-git/#ignore--dirty

laradock のsubmodule 内のファイル変更時にstatus に表示されないように修正 Close #28

---

build.sh

build.sh 内のsed コマンドのオプションを本日対面時にMac で動くように直してもらったのですが、そしたら今度はLinux 側で動かなくなってしまいました(Linux 側でも動くから大丈夫といっていたのは自分ですが…)。
なので、Mac とLinux でsed コマンドのオプションを変えるようにしました。
お手数ですがご確認よろしくおねがいします。

Mac 環境とLinux 環境とでコマンドのオプションを変更するように修正 #30

---

a6s-cloud/app/Http/Controllers/AnalysisResultListsController.php

3/24(日)ペアプロ実施時のbackend 側の修正を適用。
レスポンスで返す件数が10 件となっていますが、適切な数字は今後リファクタリング時などに検討できれば嬉しいです。

3/24(日)ペアプロ実施時のbackend 側の修正を適用 Close #39

---

a6s-cloud/app/Http/Controllers/AnalysisRequestsController.php

Laravel のFile Storage を使ってwordcloud 用のtweet データファイルを作成するように機能追加。
Laravel のFile Storage について:
https://laravel.com/docs/5.8/filesystem

wordcloud 用のtweet データファイルを作成する用に機能を追加 Close #50

---

build.sh

MySQL データを初期化する条件分岐が誤っていた(ボンミス)ためその条件分岐を修正
\#技術書典6 でPOST リクエストを飛ばして成功(tweets テーブルに何かしらの絵文字を登録)した後、build.sh を実行。エラーがなければOK
close #62
なし
特になし

build.sh でMySQL データが初期化されていなかった部分を修正

---

a6s-cloud/app/Http/Controllers/AnalysisRequestsController.php

#47 と #52  の内容を修正しました。
#64 を先にマージして、analysis_resultsテーブルにurlとretweet_countの追加をお願いします。
`http://localhost/api/v1/AnalysisRequests`にリクエストを投げて、urlとretweet_countにデータが入ることの確認をお願いします。
close #47
close #52
なし
なし

urlとretweet_countのデータを登録

---

a6s-cloud/app/Http/Controllers/AnalysisRequestsController.php

#48  の内容を修正しました。
リクエストの値でtweetデータが取得できることを確認お願いします。
※古い日付は取得できない可能性があります。
close #48
#67 
tweet件数が0件の場合に例外が発生するバグを発見しました！！
issueに追加です😎
`$carbon->format`で `2019-04-01_12:00:00_JST`までできる気が。。
これは次回のリファクタリングとかに対応したいと思ってます🙇‍♂️

パラメータに日付をバインドする処理の追加

---

a6s-cloud/app/Http/Controllers/AnalysisRequestsController.php

#70 と #72  の内容を修正しました。
- tweet取得日が下記になっていること
`<指定日時>_00:00:00_JST`〜`<指定日時>_11:59:59_JST`
- analysis_resultsテーブルのanalysis_end_dateが`<指定日時>_11:59:59`で保存されること
close #70
close #72
なし
なし

Tweet 取得時刻範囲の変更対応

---

.gitmodules
a6s-cloud/app/Http/Controllers/AnalysisRequestsController.php
build.sh

Python モジュールをworkspace コンテナにインストールしていたが、php-fpm に変更。
Laravel がバッチを叩く時はphp-fpm コンテナから叩いているため。
※前回と同様の手順
(1)手元にpull したあとコンテナを一旦削除する
```
$ pushd laradock
$ docker-compose rm -f
$ popd
```
(2)build.sh を実行してコンテナを再構築する
```
$ ./build.sh
```
(3)以下のコマンドを実行してコンテナ上でWord Cloud を実行する
※`docker exec ...` は2 行で1 コマンドです。
```
$ docker exec laradock_php-fpm_1 su - www-data -s /bin/bash -c \
'python3 a6s-cloud-batch/src/createWordCloud.py a6s-cloud-batch/test_data/tweet1.txt RictyDiminished/RictyDiminished-Bold.ttf /var/www/result.png'
$ ls -l result.png
// 対象はlaradock_php-fpm_1 コンテナです。result.png ができているはず
```
Close #81
なし
なし

Python モジュールをインストールするコンテナをphp-fpm に変更

---

a6s-cloud/app/Http/Controllers/AnalysisRequestsController.php
build.sh

Laravel からWord Cloud API を実行する処理を追加。
例えば`analysis_word=#技術書典`、`start_date=2019-04-14` でリクエストを飛ばすとそのTweet を取得してきてWord Cloud 画像を生成します。
画像は仮でリポジトリのroot にresult.png というファイルで保存されます。
Close #82  <- こちらを先にマージしてもらえると嬉しいです
Close #12
Word Cloud 画像の出力先にlocal storage を使う #84
出力したWord Cloud 画像をDB に保存する処理を追加する #85
Word Cloud 画像生成処理に失敗した時のエラー処理を追加する #86
上記issue 番号は実際にissue 建ててから編集します

Laravel からWord Cloud API を実行する処理を追加

---

a6s-cloud/app/Http/Controllers/AnalysisRequestsController.php

#84 の対応をしました。
Word Cloud の結果画像出力先をlocal storage を使うようにしました。
適当なハッシュタグ指定でPOST リクエストを飛ばしてください。
例) 2019/04/17 の夜現在トレンドに入っていたハッシュタグでリクエストを飛ばす
```
echo -en 'start_date=2019-04-17&analysis_word=#令和に恋人できるかな&url=https://github.com/nsuzuki7713/a6s-cloud-front/&analysis_timing=[1,3]' \
| curl http://localhost/api/v1/AnalysisRequests --data-binary @- > ~/result.html
```
リクエスト送信後`a6s-cloud/storage/app/` ディレクトリにWord Cloud 画像が出力されていれば成功です。
```
$ ls -l a6s-cloud/storage/app/*.png
```
close #84
#88
local storage を使うつもりが、ただ単にlocal storage のフルPATH を組み立ててWord Cloud バッチに渡すような感じになってしまいました。
より綺麗な方法があったら教えてください。

WordCloud の結果保存先にlocal storage を使うよう修正

---

a6s-cloud/app/Http/Controllers/AnalysisRequestsController.php

Word Cloud 画像生成失敗時にHTTP 500 レスポンスを返すように修正。
それに加えて、ANALSIS_RESULTS のstatus を3 に変更し、Stack Trace をログに出力するようにもした。
* Process でコマンド実行している所で、エラーがでるようにする(例: python3 -> python4 と書き換える)
* 適当なリクエストを飛ばす
例:
```
echo -en 'start_date=2019-04-20&analysis_word=#終身雇用&url=https://github.com/nsuzuki7713/a6s-cloud-front/&analysis_timing=[1,3]' | curl http://localhost/api/v1/AnalysisRequests --data-binary @-
```
* HTTP 500 のレスポンスが返ってくること
* ANALSIS_RESULTS のstatus が3 になっていること
* a6s-cloud/storage/logs 下のファイルにStack Trace が表示されること
```
[2019-04-20 03:40:33] local.DEBUG: The command "'python4' '../../a6s-cloud-batch/src/createWordCloud.py' '/var/www/a6s-cloud/storage/app/920be163-9c38-4c2c-8a53-ef3f4ed30dda.txt' '../../RictyDiminished/RictyDiminished-Bold.ttf' …
```

Word Cloud 画像生成失敗時にHTTP 500 レスポンスを返すように修正

---

a6s-cloud/app/Http/Controllers/AnalysisRequestsController.php

必須チェックのバリデーションを実装。
Twitter APIへの下記リクエストパラメータ３種に必須チェックを追加。
* start_date
* analysis_word
* analysis_timing
エンドポイント ```api/v1/AnalysisRequests``` にPOSTでリクエストしてください。
* 正常値
リクエスト例
| key | value |
| ---------- | ---- |
| start_date | 2019/04/25 |
| analysis_word | #test |
| analysis_timing | [1,3] |
* 返却値
ID
* 異常
* いずれかのkeyが存在しないこと
* いずれかの値がNULLであること
* 返却値
* リクエスト直前の画面にリダイレクトされる
close #46
#99 Requestのファサードを用いてinputを静的呼び出ししているが、バリデーションの拡張性などを考えてDIによるオブジェクト読み込みに統一したい。
直前の画面にリダイレクトされるが、SPAの場合にこれで上手くいくのか…？
参考になりそうな記事: https://qiita.com/zaburo/items/b80d4ae73efc99b41541

Add parameter validation#46

---

a6s-cloud/app/Http/Controllers/AnalysisRequestsController.php

requestファサードの利用を廃止し、requestDIに統一。
Illuminate\Support\Facades\Request から Illuminate\Http\Request に統一しました。
見た目上の挙動は変化なしなので、リグレがないか確認してください。
close #99 
~~# このタスクで発生したissue~~
ブランチ名が死ぬほどダサくてテンションが下がったので、誰かいいブランチ名あるよって人はこっそり教えてください。

requestファサードをrequestDIに変更 #99

---

a6s-cloud/app/Http/Controllers/AnalysisRequestsController.php

#106  の内容を対応となります。
実装中の動作確認でtweetするのも煩わしい気がしたのでコメントアウトでプルリク出しています。
動作確認する際はコメントを外して確認お願いします。
word cloudの画像と共にTweetされます。
※文言とかは適宜変えてもらっても大丈夫です
close #106
特になし
特になし
https://twitteroauth.com/

word cloudで投稿した際にtweetできるように機能追加

---

a6s-cloud/app/Http/Controllers/AnalysisRequestsController.php
build.sh

#98 の対応をしました
* build.sh を実行して正常にコンテナが立ち上がること
* analysis_results テーブルのimage フィールドに解析結果ファイル名が保存されていること。
* http://localhost/storage/<作成された画像ファイル名>.png にアクセスして作成されたファイルが参照できること
close #98
なし
`php artisan storage:link` すると`/a6s-cloud/public/storage` にシンボリックリンクが作成されますが、Laravel プロジェクトの.gitignore にstorage シンボリックリンクが追加されているためコミットできない(OS 環境差異を考慮しての追加？)。
なのでbuild 時にphp artisan コマンドを発行する方針で対応しました(build.sh に追加)。

解析結果画像の保存先をpublic 化

---

a6s-cloud/app/Services/TwitterClientService.php

#113 の内容を対応しました。
analysis_resultsテーブルのfavorite_countとretweet_countが膨大ではないことを確認お願いします。
※詳細の件数まではテストしていないので、雰囲気で大丈夫です。
一応retweet_countは下記SQLを実行して、phpの結果と一致したかを確認しました。
```
select sum(retweet_count) from tweets where analysis_result_id = 2 
select sum(retweet_count) from tweets where analysis_result_id = 2 and SUBSTRING(text,1,2) != "RT"
select sum(retweet_count) from tweets where analysis_result_id = 2 and SUBSTRING(text,1,2) = "RT"
```
close #113 
特になし
正規表現の条件比較も可能でした、substrのほうが早いという記事を見つけたのでsubstrを使用しました！！
https://symfoware.blog.fc2.com/blog-entry-1812.html

RTの場合いいねとRTのサマリ計算をしない

---

.gitmodules

#120 の内容を修正しました。
どこかに新規にリポジトリをclone して`fix_module_ref_to_https#120` ブランチをチェックアウトしてsubmodule コマンドを実行して問題なく成功すること。認証要求されないこと。
```
$ grep a6s-cloud-batch .gitmodules
[submodule "a6s-cloud-batch"]
path = a6s-cloud-batch
url = https://github.com/nsuzuki7713/a6s-cloud-batch.git
$ git submodule update --init --recursive
```
close #120
なし
なし

Fix module ref to https#120

---

a6s-cloud/composer.json
a6s-cloud/composer.lock
a6s-cloud/config/app.php

#115 の内容を修正しました。
最初に `composer install` をしてください。(`./build.sh` の実行でも大丈夫なはずです！！)
解析結果一覧画面と解析結果画面のレスポンスがキャメルケースになっていることの確認をお願いします。
※Front側でキャメルに対応していないため、データが表示されなくなっています。
close #115
フロント側の修正が必要となります。
https://github.com/nsuzuki7713/a6s-cloud-front/issues/83
https://github.com/nsuzuki7713/a6s-cloud-front/issues/84
とくになし
https://github.com/grohiro/laravel-camelcase-json
https://qiita.com/grohiro/items/34984cf226f7a3593a99

camelに変換するプラグインを追加

---

a6s-cloud/app/Services/TwitterClientService.php

#128 の内容を修正しました。
1000件以上ありそうな検索ワード解析して確認お願いします。
`打ち上げ成功` のキーワードで解析した所、3814ツイート取得できました。(5分ぐらいで終わった)
下記のSQLを叩きながら状況をみました。
`select count(*) from tweets where analysis_result_id = 【解析ID】`
close #128 
とくになし
トレンドで見ると `打ち上げ成功` は5000ツイート以上あったのですが3000件しか取得できなかったです。。

tweet取得上限を5000件に変更

---

a6s-cloud/app/Http/Middleware/Cors.php

#134 の内容を修正しました。
コントローラに処理が渡る前に、リクエストパラメータのkey を一律スネークケースに変更。
キャメルケースのリクエストパラメータを投げて、正常に処理が終了することを確認
例)
```
echo -en 'startDate=2019-05-04&analysisWord=#打ち上げ成功&url=https://github.com/nsuzuki7713/a6s-cloud-front/&analysisTiming=[1,3]' | curl http://localhost/api/v1/AnalysisRequests --data-binary @- 
```
close #134
https://github.com/nsuzuki7713/a6s-cloud-front/issues/91
このタスクで発生したissue は画面側から実際に解析依頼出した時にvalidation で引っかかったため気づきました…。

フロント側からのキャメルケースリクエストをスネークケースに変更する処理を追加

---

a6s-cloud/app/Facades/ScrapingService.php
a6s-cloud/app/Providers/AppServiceProvider.php
a6s-cloud/app/Services/ScrapingService.php
a6s-cloud/composer.json
a6s-cloud/composer.lock
a6s-cloud/config/app.php

#129 の内容を修正しました。
responseで返すような実装にはしていないです。
responseで返すような実装をしていないので、`artisan tinker` (対話型処理)から確認をお願いします。
1. `./build.sh` を実行して、composer installをする
2. dockerのlaravelプロジェクトに移動
```
cd laradock
docker-compose exec workspace /bin/bash
su - laradock
cd /var/www/a6s-cloud
```
3. `artisan tinker` を実行
4. `ScrapingService::getConnpassData(128855)` を実行
5. 下記結果になっていることの確認
```
>>> ScrapingService::getConnpassData(128855)
=> [
"owner_display_name" => "OSCA",
"hash_tag" => "WEM13",
"title" => "WEBエンジニア勉強会 #13 (東京都, 渋谷)",
"waiting" => 1,
"limit" => 76,
"accepted" => 58,
"catch" => "東京都開催、初心者でも参加できるWEBエンジニアのための勉強会コミュニティ",
"place" => "株式会社ミクシィ",
"address" => "東京都渋谷区東1-2-20 住友不動産渋谷ファーストタワー7F",
"started_at" => "2019-05-24T19:15:00+09:00",
]
```
close #129 
とくになし
この処理をFacadeとServiceに登録したほうがいいものなのかよく分かっていない。。 …

Connpass APIを使用して情報を取得

---

a6s-cloud/app/BlackAnalysisWords.php
a6s-cloud/app/Http/Controllers/AnalysisRequestsController.php
a6s-cloud/app/Rules/NGAnalysisWord.php

#142 の内容を修正しました。
まず、テーブルにNGワードを追加してください
例) #editor_war を追加する場合
```
INSERT INTO black_analysis_words (analysis_ng_word, availability_flag) VALUES ('#editor_war', 0);
```
登録したワードで解析依頼を出してください。
例)curl の場合
```
echo -en 'start_date=2019-05-07&analysis_word=#editor_war&url=https://github.com/nsuzuki7713/a6s-cloud-front/&analysis_timing=[1,3]' \
| curl http://localhost/api/v1/AnalysisRequests --data-binary @-
```
close #142
なし
重複した解析ワードと日付と同様なロジックで実装しておきました。

NGワードで解析依頼できないよに修正

---

a6s-cloud/public/swagger-ui/swagger.yml

#143 の内容を修正しました。
`http://localhost/swagger-ui` にアクセスしてAnalysisResultsが追加されていることの確認お願いします。
`Example Value / Model` を切り替えると項目の詳細情報とかが見れます！！
close #143
とくになし
APIが増えた時に1ファイルに追記するのはつらみがある予感。。

AnalysisResults APIをswaggerに追加

---

a6s-cloud/app/Console/Kernel.php
a6s-cloud/app/Schedules/BatchedAnalysisRequests.php
a6s-cloud/app/Services/AnalysisRequestService.php
build.sh

#130 の内容を実装しました。
* build.sh を実行して再度コンテナ環境を構築しなおしてください
```
./build.sh
```
* 昨日以前、本日以前、明日以降と解析依頼レコードを作成して、昨日以前のレコードのみ処理されることを確認してください。解析は10分単位で走ります
```
-- SQL 例
INSERT INTO analysis_results (analysis_start_date, analysis_end_date, analysis_word, status) VALUES ('2019-05-10 00:00:00', '2019-05-10 23:59:59', '#Google', 0);
INSERT INTO analysis_results (analysis_start_date, analysis_end_date, analysis_word, status) VALUES ('2019-05-11 00:00:00', '2019-05-11 23:59:59', '#Google', 0);
INSERT INTO analysis_results (analysis_start_date, analysis_end_date, analysis_word, status) VALUES ('2019-05-12 00:00:00', '2019-05-11 23:59:59', '#Google', 0);
```
* ログを見て処理されたことを確認してください(`/storage/logs/laravel-YYYY-MM-DD.log`)
* フロントも起動して解析結果一覧を表示すると、昨日以前のやつだけ処理されていることが確認できると思います
close #130
#152 …

解析依頼バッチ処理の追加

---

a6s-cloud/app/Http/Controllers/AnalysisResultsController.php
a6s-cloud/routes/api.php

#154 の内容を修正しました。
DELETE メソッドで削除対象の解析依頼のリクエストを飛ばしてください。
例) curl の場合
```
curl -X "DELETE" http://localhost/api/v1/AnalysisResults/1
```
そのあと、解析結果が削除されていることを確認願います。
close #154
なし
なし

解析結果の削除用エンドポイントを追加

---

a6s-cloud/app/Http/Controllers/AnalysisRequestsController.php
a6s-cloud/composer.json
a6s-cloud/composer.lock
a6s-cloud/config/app.php
a6s-cloud/config/services.php

#139 の内容を修正しました。
コードとslackの`#grouscope_applog`で通知内容の雰囲気を確認できます。
もし動作確認する場合は下記の手順で確認できます。
1. composer install
laravel-slack-apiをインストール
2. `.env` にtokenを記載
```
SLACK_TOKEN="slackで別途共有します"
```
3. AnalysisRequestsControllerの44行目周辺のコメントを外す
```
// 開発時に出力しないためにコメントアウト
SlackFile::upload([
'filename' => 'wordCloudError.txt',
'content' => $e->getMessage().$e->getTraceAsString(),
'channels' => '#grouscope_applog',
'initial_comment' => 'WordCloudの処理でエラーがでたよー:sob:'
]);
```
4. AnalysisRequestServiceのrunWordCloudを下記に変更
python4にすることで強制的にエラーにする
```
$process = new Process([
'python4',
base_path() . '/../a6s-cloud-batch/src/createWordCloud.py',
$this->localStoragePath . $this->getTweetsFileForWordcloud(),
base_path() . '/../RictyDiminished/RictyDiminished-Bold.ttf',
$this->publicStoragePath . …
```

アプリケーションエラーをslackへ通知する

---

docker/nginx/Dockerfile
docker/nginx/default.conf

#163 の内容に対応しました。
// イメージは既にDocker Hub 上にアップされた状態になっています。
ターミナル1 を開き、以下のコマンドを実行します。laradock 等の80 番ポートを使っているアプリがあれば、それは落としておいてください。
```
$ docker run --rm -p 80:80 -ti a6scloud/grouscope-nginx:testing
// testing タグ付きで実行します。コマンド実行後、待受の状態になります
```
ターミナル2 を開き、以下のようにcurl コマンドを実行します。
```
curl http://localhost
```
ターミナル1 にエラーログが出ること。
```
2019/07/15 09:06:34 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.0.1, server: default_server, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:1008
0"
2019/07/15 09:06:34 [warn] 6#6: *1 upstream server temporarily disabled while connecting to upstream, client: 172.17.0.1, server: default_server, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: …
```

nginx イメージを作成
